/**
 * Initial data for the Documentation & Governance Checklist
 * Seeded from Documentation_Checklist.xlsx
 */

export const INITIAL_DOC_CHECKLIST = [
  // ── 1. System Architecture ──────────────────────────────────────────────
  {
    id: "1.1",
    section: "System Architecture",
    task: "Create high-level system architecture diagram (Frontend → Backend → DB → Payments → Hosting)",
    category: "Architecture",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Diagram (PNG/PDF)",
    notes: "",
  },
  {
    id: "1.2",
    section: "System Architecture",
    task: "Document frontend structure (folder layout, routing, state mgmt)",
    category: "Architecture",
    owner: "Nhlanhla",
    priority: "High",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },
  {
    id: "1.3",
    section: "System Architecture",
    task: "Document backend architecture (services, controllers, logic layers)",
    category: "Architecture",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },
  {
    id: "1.4",
    section: "System Architecture",
    task: "Document BIG Score logic (rule-based structure + scoring weights overview)",
    category: "Architecture",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },
  {
    id: "1.5",
    section: "System Architecture",
    task: "Document SME-Funder matching logic & tables",
    category: "Architecture",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },

  // ── 2. Database & Data Structure ────────────────────────────────────────
  {
    id: "2.1",
    section: "Database & Data Structure",
    task: "Export and document full database schema",
    category: "Database",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "ER diagram",
    notes: "",
  },
  {
    id: "2.2",
    section: "Database & Data Structure",
    task: "Document core tables (Users, SMEs, Funders, Scores, Matches)",
    category: "Database",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },
  {
    id: "2.3",
    section: "Database & Data Structure",
    task: "Document relationships between key tables",
    category: "Database",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Diagram",
    notes: "",
  },
  {
    id: "2.4",
    section: "Database & Data Structure",
    task: "Define data validation rules",
    category: "Database",
    owner: "Nhlanhla",
    priority: "Medium",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },
  {
    id: "2.5",
    section: "Database & Data Structure",
    task: "Confirm database backup procedure",
    category: "Database",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Written process",
    notes: "",
  },

  // ── 3. Deployment & Hosting ─────────────────────────────────────────────
  {
    id: "3.1",
    section: "Deployment & Hosting",
    task: "Document hosting provider(s)",
    category: "Deployment",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },
  {
    id: "3.2",
    section: "Deployment & Hosting",
    task: "Document deployment steps (dev → prod)",
    category: "Deployment",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Step guide",
    notes: "",
  },
  {
    id: "3.3",
    section: "Deployment & Hosting",
    task: "List environment variables required (without secrets)",
    category: "Deployment",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Secure doc",
    notes: "",
  },
  {
    id: "3.4",
    section: "Deployment & Hosting",
    task: "Confirm separation of dev / staging / prod",
    category: "Deployment",
    owner: "Lindelani",
    priority: "Medium",
    status: "Not Started",
    deliverable: "Status note",
    notes: "",
  },
  {
    id: "3.5",
    section: "Deployment & Hosting",
    task: "Document rollback procedure",
    category: "Deployment",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Step guide",
    notes: "",
  },

  // ── 4. Payments & Financial Flow ────────────────────────────────────────
  {
    id: "4.1",
    section: "Payments & Financial Flow",
    task: "Document payment gateway integration flow",
    category: "Payments",
    owner: "Nhlanhla",
    priority: "High",
    status: "Not Started",
    deliverable: "Flow diagram",
    notes: "",
  },
  {
    id: "4.2",
    section: "Payments & Financial Flow",
    task: "Document webhook handling logic",
    category: "Payments",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },
  {
    id: "4.3",
    section: "Payments & Financial Flow",
    task: "Map payment failure handling",
    category: "Payments",
    owner: "Nhlanhla",
    priority: "Medium",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },
  {
    id: "4.4",
    section: "Payments & Financial Flow",
    task: "Confirm subscription logic structure",
    category: "Payments",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Notion page",
    notes: "",
  },

  // ── 5. Third-Party Services & Dependencies ──────────────────────────────
  {
    id: "5.1",
    section: "Third-Party Services & Dependencies",
    task: "List all third-party services used",
    category: "Governance",
    owner: "Both",
    priority: "High",
    status: "Not Started",
    deliverable: "Master list",
    notes: "",
  },
  {
    id: "5.2",
    section: "Third-Party Services & Dependencies",
    task: "Identify purpose of each service",
    category: "Governance",
    owner: "Both",
    priority: "High",
    status: "Not Started",
    deliverable: "Description",
    notes: "",
  },
  {
    id: "5.3",
    section: "Third-Party Services & Dependencies",
    task: "Document API dependencies",
    category: "Governance",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "API inventory",
    notes: "",
  },
  {
    id: "5.4",
    section: "Third-Party Services & Dependencies",
    task: "Confirm current access levels per service",
    category: "Governance",
    owner: "Thando (private)",
    priority: "High",
    status: "Not Started",
    deliverable: "Private audit",
    notes: "",
  },

  // ── 6. Security & Governance ────────────────────────────────────────────
  {
    id: "6.1",
    section: "Security & Governance",
    task: "Confirm 2FA enabled across all critical systems",
    category: "Security",
    owner: "Both",
    priority: "High",
    status: "Not Started",
    deliverable: "Confirmation",
    notes: "",
  },
  {
    id: "6.2",
    section: "Security & Governance",
    task: "Confirm no shared passwords in codebase",
    category: "Security",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Verification note",
    notes: "",
  },
  {
    id: "6.3",
    section: "Security & Governance",
    task: "Confirm secrets not stored in repo",
    category: "Security",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Verification note",
    notes: "",
  },
  {
    id: "6.4",
    section: "Security & Governance",
    task: "Document access control structure",
    category: "Security",
    owner: "Both",
    priority: "Medium",
    status: "Not Started",
    deliverable: "Access map",
    notes: "",
  },

  // ── 7. Operational Continuity ───────────────────────────────────────────
  {
    id: "7.1",
    section: "Operational Continuity",
    task: "Document full system restart process",
    category: "Ops",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "Step guide",
    notes: "",
  },
  {
    id: "7.2",
    section: "Operational Continuity",
    task: "Document new user onboarding flow",
    category: "Ops",
    owner: "Nhlanhla",
    priority: "Medium",
    status: "Not Started",
    deliverable: "Flow doc",
    notes: "",
  },
  {
    id: "7.3",
    section: "Operational Continuity",
    task: "Document SME scoring process (manual override if needed)",
    category: "Ops",
    owner: "Lindelani",
    priority: "High",
    status: "Not Started",
    deliverable: "SOP",
    notes: "",
  },
  {
    id: "7.4",
    section: "Operational Continuity",
    task: "Document release process for updates",
    category: "Ops",
    owner: "Lindelani",
    priority: "Medium",
    status: "Not Started",
    deliverable: "SOP",
    notes: "",
  },
];

export const SECTION_COLORS = {
  "System Architecture": "rgba(59,130,246,0.12)",
  "Database & Data Structure": "rgba(34,197,94,0.12)",
  "Deployment & Hosting": "rgba(234,179,8,0.12)",
  "Payments & Financial Flow": "rgba(168,85,247,0.12)",
  "Third-Party Services & Dependencies": "rgba(249,115,22,0.12)",
  "Security & Governance": "rgba(239,68,68,0.12)",
  "Operational Continuity": "rgba(107,114,128,0.12)",
};

export const SECTION_BADGE_COLORS = {
  "System Architecture": "#3b82f6",
  "Database & Data Structure": "#22c55e",
  "Deployment & Hosting": "#eab308",
  "Payments & Financial Flow": "#a855f7",
  "Third-Party Services & Dependencies": "#f97316",
  "Security & Governance": "#ef4444",
  "Operational Continuity": "#6b7280",
};
