import { colors } from "../../shared/theme";

const getSubStyles = (currentSidebarOpen, currentSidebarWidth) => ({
  container: {
    minHeight: "100vh",
    padding: "1rem",
    fontFamily: "'Inter', 'Segoe UI', 'Roboto', sans-serif",
    boxSizing: "border-box",
    marginLeft: currentSidebarOpen ? `${currentSidebarWidth}px` : "0px",
    transition: "all 0.3s ease",
  },
  mainCard: {
    background: `linear-gradient(135deg, ${colors.offWhite} 0%, ${colors.cream} 100%)`,
    borderRadius: "24px",
    padding: "clamp(1rem, 3vw, 2rem)",
    boxShadow: `0 20px 60px ${colors.darkBrown}15, 0 8px 24px ${colors.darkBrown}0A`,
    border: `1px solid ${colors.lightTan}`,
    position: "relative",
    overflow: "hidden",
    maxWidth: "100%",
    margin: "0 auto",
  },
  decorativeElement: {
    position: "absolute",
    top: "-100px",
    right: "-100px",
    width: "300px",
    height: "300px",
    background: `radial-gradient(circle, ${colors.accentGold}14 0%, transparent 70%)`,
    borderRadius: "50%",
    pointerEvents: "none",
  },
  pageTitle: {
    fontSize: "clamp(2rem, 4vw, 2.75rem)",
    fontWeight: 800,
    background: `linear-gradient(135deg, ${colors.darkBrown} 0%, ${colors.mediumBrown} 100%)`,
    backgroundClip: "text",
    WebkitBackgroundClip: "text",
    color: "transparent",
    textAlign: "center",
    marginBottom: "1rem",
    letterSpacing: "-1.5px",
    lineHeight: "1.2",
  },
  subtitle: {
    fontSize: "clamp(1rem, 2vw, 1.125rem)",
    color: colors.mediumBrown,
    textAlign: "center",
    marginBottom: "3rem",
    fontWeight: 400,
    opacity: 0.9,
  },
  betaNotice: {
    background: `linear-gradient(135deg, ${colors.trialBrown}20 0%, ${colors.accentGold}20 100%)`,
    color: colors.darkBrown,
    border: `2px solid ${colors.trialBrown}`,
    borderRadius: "16px",
    padding: "1.5rem 2rem",
    margin: "0 auto 3rem auto",
    maxWidth: "800px",
    fontWeight: 600,
    fontSize: "clamp(1rem, 2vw, 1.125rem)",
    textAlign: "center",
    boxShadow: `0 8px 24px ${colors.trialBrown}1F`,
    position: "relative",
  },
  betaIcon: {
    display: "inline-block",
    marginRight: "0.5rem",
    fontSize: "1.25rem",
  },
  billingToggleContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: "2rem auto",
    gap: "1rem",
  },
  billingToggle: {
    display: "flex",
    background: colors.cream,
    borderRadius: "12px",
    padding: "4px",
    border: `1px solid ${colors.lightTan}`,
    boxShadow: `0 4px 12px ${colors.darkBrown}0A`,
  },
  billingToggleOption: {
    padding: "0.75rem 1.5rem",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.95rem",
    transition: "all 0.3s ease",
    color: colors.mediumBrown,
    position: "relative",
  },
  billingToggleActive: {
    background: colors.accentGold,
    color: colors.lightText,
    boxShadow: `0 2px 8px ${colors.accentGold}33`,
  },
  savingsBadge: {
    background: colors.mediumBrown,
    color: colors.lightText,
    fontSize: "0.75rem",
    padding: "0.25rem 0.5rem",
    borderRadius: "6px",
    fontWeight: 700,
    marginLeft: "0.5rem",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  featureComparisonContainer: {
    margin: "3rem auto",
    maxWidth: "100%",
    background: `linear-gradient(135deg, ${colors.offWhite} 0%, ${colors.cream} 100%)`,
    borderRadius: "20px",
    padding: "1.5rem",
    boxShadow: `0 12px 40px ${colors.darkBrown}0A`,
    border: `1px solid ${colors.lightTan}`,
    overflow: "auto",
  },
  featureComparisonTitle: {
    fontSize: "clamp(1.25rem, 3vw, 1.75rem)",
    fontWeight: 700,
    color: colors.darkBrown,
    marginBottom: "2rem",
    textAlign: "center",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    alignItems: "center",
  },
  featureComparisonTable: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: "0",
    background: colors.offWhite,
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: `0 4px 12px ${colors.darkBrown}0A`,
    border: `1px solid ${colors.lightTan}`,
    fontSize: "clamp(0.8rem, 1.5vw, 0.95rem)",
  },
  featureTh: {
    background: `linear-gradient(135deg, ${colors.cream} 0%, ${colors.lightTan} 100%)`,
    fontWeight: 700,
    padding: "1rem",
    color: colors.darkBrown,
    fontSize: "clamp(0.9rem, 1.5vw, 1.05rem)",
    borderBottom: `2px solid ${colors.lightTan}`,
    position: "relative",
  },
  featureTd: {
    padding: "0.75rem",
    textAlign: "center",
    fontSize: "clamp(0.8rem, 1.5vw, 0.95rem)",
    color: colors.mediumBrown,
    borderBottom: `1px solid ${colors.lightTan}26`,
    transition: "background-color 0.2s ease",
  },
  featureTdLeft: {
    textAlign: "left",
    fontWeight: 600,
    color: colors.darkBrown,
  },
  annualDiscount: {
    marginTop: "1.5rem",
    padding: "1rem",
    background: colors.cream,
    border: `1px solid ${colors.lightTan}`,
    borderRadius: "8px",
    fontSize: "clamp(0.8rem, 1.5vw, 0.9rem)",
    color: colors.darkBrown,
  },
  planGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(200px, 1fr))",
    gap: "1.5rem",
    margin: "3rem 0",
    justifyContent: "center",
    maxWidth: "100%",
  },
  planCard: {
    background: colors.offWhite,
    border: `1px solid ${colors.lightTan}`,
    borderRadius: "16px",
    padding: "2rem",
    textAlign: "center",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    cursor: "pointer",
    boxShadow: `0 8px 24px ${colors.darkBrown}14`,
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minHeight: "450px",
  },
  planCardPopular: {
    background: colors.engageCardBg,
    color: colors.lightText,
    transform: "scale(1.03)",
    zIndex: 2,
    boxShadow: `0 20px 60px ${colors.darkBrown}33`,
    border: `1px solid ${colors.accentGold}`,
  },
  planCardHover: {
    // transform: "translateY(-8px)",
    // boxShadow: `0 16px 40px ${colors.darkBrown}26`,
  },
  planCardSelected: {
    border: `2px solid ${colors.accentGold}`,
    boxShadow: `0 12px 30px ${colors.accentGold}33`,
  },
  popularBadge: {
    position: "absolute",
    top: "0.8rem",
    right: "0.8rem",
    background: colors.accentGold,
    color: colors.lightText,
    padding: "0.4rem 1rem",
    borderRadius: "20px",
    fontSize: "0.8rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.8px",
    boxShadow: `0 2px 8px ${colors.accentGold}4D`,
  },
  planName: {
    fontSize: "clamp(1.75rem, 3vw, 2.25rem)",
    fontWeight: 800,
    marginBottom: "0.75rem",
    letterSpacing: "-1px",
    color: colors.lightText,
  },
  planPrice: {
    fontSize: "clamp(2.5rem, 4vw, 3.5rem)",
    fontWeight: 900,
    marginBottom: "0.5rem",
    lineHeight: "1",
    color: colors.lightText,
  },
  planPriceFree: {
    color: colors.lightText,
    fontSize: "clamp(2.5rem, 4vw, 3.5rem)",
    fontWeight: 900,
  },
  planPricePeriod: {
    fontSize: "clamp(1rem, 1.5vw, 1.25rem)",
    fontWeight: 500,
    opacity: 0.8,
    color: colors.lightText,
  },
  planDescriptionText: {
    fontSize: "clamp(0.9rem, 1.5vw, 1rem)",
    color: colors.lightText,
    marginBottom: "2rem",
    lineHeight: "1.6",
  },
  freeMonthsBadge: {
    background: `linear-gradient(90deg, ${colors.trialBrown} 0%, ${colors.accentGold} 100%)`,
    color: colors.lightText,
    padding: "0.8rem 1.2rem",
    borderRadius: "12px",
    fontSize: "1rem",
    fontWeight: 700,
    marginBottom: "1rem",
    textAlign: "center",
    boxShadow: `0 4px 12px ${colors.trialBrown}4D`,
    display: "inline-block",
    border: `2px solid ${colors.trialBrown}`,
  },
  afterTrialPrice: {
    background: `linear-gradient(135deg, ${colors.cream} 0%, ${colors.lightTan} 100%)`,
    border: `1px solid ${colors.lightTan}`,
    borderRadius: "8px",
    padding: "0.8rem",
    marginBottom: "1.5rem",
    fontSize: "0.9rem",
    color: colors.mediumBrown,
    fontWeight: 600,
  },
  planFeaturesList: {
    listStyle: "none",
    padding: "0",
    margin: "0 0 2.5rem 0",
    flex: 1,
    textAlign: "left",
  },
  planFeatureItem: {
    padding: "0.6rem 0",
    fontSize: "clamp(0.9rem, 1.5vw, 1rem)",
    display: "flex",
    alignItems: "center",
    lineHeight: "1.5",
    color: colors.lightText,
  },
  featureIcon: {
    marginRight: "0.8rem",
    fontSize: "1.1rem",
    flexShrink: 0,
  },
  featureCheckIcon: {
    color: colors.featureCheck,
  },
  featureCrossIcon: {
    color: colors.featureCross,
  },
  currentPlanBadge: {
    display: "inline-block",
    background: colors.accentGold,
    color: colors.lightText,
    fontWeight: 600,
    borderRadius: "8px",
    padding: "0.5rem 1rem",
    fontSize: "0.875rem",
    letterSpacing: "0.5px",
  },
  selectedBadge: {
    display: "inline-block",
    background: colors.mediumBrown,
    color: colors.lightText,
    fontWeight: 600,
    borderRadius: "8px",
    padding: "0.5rem 1rem",
    fontSize: "0.875rem",
    letterSpacing: "0.5px",
  },
  selectButton: {
    width: "100%",
    padding: "1rem 2rem",
    background: `linear-gradient(135deg, ${colors.accentGold} 0%, ${colors.mediumBrown} 100%)`,
    color: colors.lightText,
    border: "none",
    borderRadius: "10px",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: "clamp(1rem, 1.8vw, 1.1rem)",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.75rem",
    marginTop: "auto",
    boxShadow: `0 6px 18px ${colors.accentGold}4D`,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  addOnsSection: {
    margin: "3rem auto",
    maxWidth: "100%",
    background: `linear-gradient(135deg, ${colors.offWhite} 0%, ${colors.cream} 100%)`,
    borderRadius: "20px",
    padding: "2rem",
    boxShadow: `0 12px 40px ${colors.darkBrown}0A`,
    border: `1px solid ${colors.lightTan}`,
  },
  addOnsTitle: {
    fontSize: "clamp(1.25rem, 3vw, 1.75rem)",
    fontWeight: 700,
    color: colors.darkBrown,
    marginBottom: "2rem",
    textAlign: "left",
  },
  addOnsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(250px, 1fr))",
    gap: "1.5rem",
  },
  addOnItem: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "1.5rem",
    background: colors.offWhite,
    border: `1px solid ${colors.lightTan}`,
    borderRadius: "12px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    minHeight: "150px",
  },
  addOnName: {
    fontWeight: 600,
    color: colors.darkBrown,
    fontSize: "clamp(0.9rem, 1.5vw, 1rem)",
    marginBottom: "0.5rem",
  },
  addOnDescription: {
    fontSize: "clamp(0.8rem, 1.5vw, 0.9rem)",
    color: colors.mediumBrown,
    marginBottom: "1rem",
    lineHeight: "1.4",
    flex: 1,
  },
  addOnPrice: {
    fontWeight: 700,
    color: colors.accentGold,
    fontSize: "clamp(0.95rem, 1.5vw, 1.1rem)",
    textAlign: "center",
    padding: "0.5rem",
    background: `linear-gradient(135deg, ${colors.cream} 0%, ${colors.lightTan} 100%)`,
    borderRadius: "8px",
    border: `1px solid ${colors.lightTan}`,
  },
  downgradeSection: {
    textAlign: "center",
    margin: "2.5rem 0",
    padding: "2rem",
    background: `linear-gradient(135deg, ${colors.cream} 0%, ${colors.lightTan} 100%)`,
    borderRadius: "16px",
    border: `1px solid ${colors.lightTan}`,
  },
  button: {
    padding: "1rem 2rem",
    background: `linear-gradient(135deg, ${colors.accentGold} 0%, ${colors.mediumBrown} 100%)`,
    color: colors.lightText,
    border: "none",
    borderRadius: "12px",
    fontWeight: 700,
    fontSize: "clamp(0.9rem, 1.5vw, 1rem)",
    cursor: "pointer",
    margin: "0.5rem",
    transition: "all 0.3s ease",
    boxShadow: `0 4px 12px ${colors.accentGold}4D`,
    letterSpacing: "0.5px",
    textTransform: "uppercase",
  },
  buttonSecondary: {
    background: `linear-gradient(135deg, ${colors.lightTan} 0%, ${colors.cream} 100%)`,
    color: colors.darkBrown,
    border: `2px solid ${colors.lightTan}`,
    fontWeight: 700,
    borderRadius: "12px",
    padding: "1rem 2rem",
    fontSize: "clamp(0.9rem, 1.5vw, 1rem)",
    cursor: "pointer",
    margin: "0.5rem",
    transition: "all 0.3s ease",
    boxShadow: `0 4px 12px ${colors.lightTan}33`,
    letterSpacing: "0.5px",
    textTransform: "uppercase",
  },
  planChangeModal: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: `${colors.darkBrown}66`,
    backdropFilter: "blur(8px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    animation: "fadeIn 0.3s ease",
    padding: "1rem",
    boxSizing: "border-box",
  },
  modalContent: {
    background: `linear-gradient(135deg, ${colors.offWhite} 0%, ${colors.cream} 100%)`,
    padding: "2rem",
    borderRadius: "24px",
    maxWidth: "500px",
    width: "100%",
    boxShadow: `0 24px 60px ${colors.darkBrown}33`,
    textAlign: "center",
    border: `1px solid ${colors.lightTan}`,
    position: "relative",
    maxHeight: "90vh",
    overflow: "auto",
  },
  modalTitle: {
    fontSize: "clamp(1.25rem, 3vw, 1.75rem)",
    fontWeight: 800,
    color: colors.darkBrown,
    marginBottom: "1rem",
    letterSpacing: "-0.5px",
  },
  modalText: {
    fontSize: "clamp(1rem, 2vw, 1.125rem)",
    color: colors.mediumBrown,
    marginBottom: "2rem",
    lineHeight: "1.6",
  },
  modalActions: {
    display: "flex",
    justifyContent: "center",
    gap: "1rem",
    marginTop: "2rem",
    flexWrap: "wrap",
  },
  paymentButton: {
    padding: "1rem 2rem",
    background: `linear-gradient(135deg, ${colors.accentGold} 0%, ${colors.mediumBrown} 100%)`,
    color: colors.lightText,
    border: "none",
    borderRadius: "12px",
    fontWeight: 700,
    fontSize: "1rem",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: `0 4px 12px ${colors.accentGold}4D`,
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    minWidth: "200px",
    minHeight: "50px",
  },
  paymentButtonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
    background: `linear-gradient(135deg, ${colors.lightTan} 0%, ${colors.cream} 100%)`,
    color: colors.mediumBrown,
    boxShadow: `0 2px 8px ${colors.lightTan}33`,
  },
  subscriptionInfo: {
    background: `linear-gradient(135deg, ${colors.cream} 0%, ${colors.lightTan} 100%)`,
    borderRadius: "16px",
    padding: "1.5rem",
    marginBottom: "2rem",
    border: `1px solid ${colors.lightTan}`,
  },
  subscriptionTitle: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: colors.darkBrown,
    marginBottom: "1rem",
  },
  subscriptionDetail: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.5rem 0",
    fontSize: "1rem",
    color: colors.darkText,
    borderBottom: `1px solid ${colors.lightTan}33`,
  },
});

const getBillingHistoryStyles = (
  isSidebarCollapsed = false,
  userType = "investor",
) => {
  // Base styles common to all user types
  const baseStyles = {
    // Container styles
    billingContainer: {
      maxWidth: "none",
      margin: "5rem 2rem 2rem 280px",
      padding: "0",
      backgroundColor: colors.offWhite,
      borderRadius: "1.25rem",
      boxShadow: `0 10px 25px ${colors.darkBrown}1A`,
      border: `1px solid ${colors.lightTan}`,
      overflow: "hidden",
    },

    billingContainerDynamic: {
      maxWidth: "none",
      marginLeft: isSidebarCollapsed ? "80px" : "280px",
      marginTop: "72px",
      marginBottom: "2rem",
      padding: "0",
      backgroundColor: colors.offWhite,
      borderRadius: "1.25rem",
      boxShadow: `0 10px 25px ${colors.darkBrown}1A`,
      border: `1px solid ${colors.lightTan}`,
      overflow: "hidden",
      transition: "all 0.3s ease",
    },

    // Typography
    sectionTitle: {
      fontSize: "1.75rem",
      fontWeight: 700,
      color: colors.darkBrown,
      marginBottom: "2rem",
      letterSpacing: "-0.025em",
    },

    // Tab Navigation
    tabNavigation: {
      display: "flex",
      backgroundColor: colors.cream,
      borderBottom: `1px solid ${colors.lightTan}`,
      padding: "0",
    },

    tabButton: {
      padding: "1rem 2rem",
      fontWeight: 600,
      textAlign: "center",
      transition: "all 0.3s ease",
      cursor: "pointer",
      border: "none",
      fontSize: "0.9rem",
      letterSpacing: "0.025em",
      position: "relative",
      color: colors.mediumBrown,
    },

    tabButtonActive: {
      backgroundColor: colors.accentGold,
      color: colors.lightText,
      boxShadow: `inset 0 2px 4px ${colors.darkBrown}1A`,
    },

    tabButtonInactive: {
      backgroundColor: "transparent",
      color: colors.darkBrown,
    },

    tabButtonInactiveHover: {
      backgroundColor: colors.cream,
      color: colors.darkBrown,
    },

    tabContent: {
      padding: "2.5rem 3rem",
      backgroundColor: colors.offWhite,
    },

    // Table Styles
    tableResponsive: {
      width: "100%",
      overflowX: "auto",
      backgroundColor: colors.offWhite,
      borderRadius: "1rem",
      padding: "1rem",
      border: `1px solid ${colors.lightTan}`,
    },

    transactionTable: {
      width: "100%",
      borderCollapse: "collapse",
      fontSize: "0.875rem",
      backgroundColor: colors.offWhite,
      borderRadius: "0.75rem",
      overflow: "hidden",
      border: `1px solid ${colors.lightTan}`,
      boxShadow: `0 4px 12px ${colors.darkBrown}1A`,
    },

    transactionThTd: {
      padding: "1rem 1.25rem",
      border: `1px solid ${colors.lightTan}`,
      textAlign: "left",
      verticalAlign: "middle",
      color: colors.darkBrown,
    },

    transactionTh: {
      backgroundColor: colors.cream,
      fontWeight: 600,
      color: colors.darkBrown,
      fontSize: "0.85rem",
      letterSpacing: "0.025em",
    },

    transactionId: {
      fontFamily: "monospace",
      fontSize: "0.75rem",
      backgroundColor: colors.offWhite,
      padding: "0.25rem 0.5rem",
      borderRadius: "0.375rem",
      color: colors.darkBrown,
      border: `1px solid ${colors.lightTan}`,
    },

    datetimeCell: {
      display: "flex",
      flexDirection: "column",
      fontSize: "0.875rem",
      color: colors.mediumBrown,
    },

    // Amount Styles
    amountFree: {
      color: colors.featureCheck,
      fontWeight: 600,
    },

    amountPaid: {
      color: colors.darkBrown,
      fontWeight: 600,
    },

    // Status Badges
    statusBadgeSuccess: {
      backgroundColor: colors.cream,
      color: colors.darkBrown,
      padding: "0.35rem 0.8rem",
      borderRadius: "9999px",
      fontSize: "0.75rem",
      fontWeight: 600,
      textTransform: "capitalize",
      border: `1px solid ${colors.lightTan}`,
    },

    statusBadge: {
      display: "inline-block",
      padding: "0.35rem 0.8rem",
      borderRadius: "9999px",
      fontSize: "0.75rem",
      fontWeight: 600,
      textTransform: "capitalize",
      border: "1px solid",
    },

    statusSuccess: {
      backgroundColor: colors.cream,
      color: colors.featureCheck,
      borderColor: colors.lightTan,
    },

    statusCancelled: {
      backgroundColor: colors.cream,
      color: colors.mediumBrown,
      borderColor: colors.lightTan,
    },

    statusActive: {
      backgroundColor: colors.cream,
      color: colors.mediumBrown,
      borderColor: colors.lightTan,
    },

    // Action Buttons
    actionButtons: {
      display: "flex",
      gap: "0.5rem",
      flexWrap: "wrap",
    },

    downloadBtn: {
      display: "flex",
      alignItems: "center",
      gap: "0.3rem",
      backgroundColor: colors.accentGold,
      color: colors.lightText,
      border: "none",
      padding: "0.5rem 0.85rem",
      fontSize: "0.75rem",
      borderRadius: "0.5rem",
      cursor: "pointer",
      transition: "all 0.3s ease",
      fontWeight: 500,
      boxShadow: `0 2px 4px ${colors.accentGold}33`,
    },

    downloadBtnHover: {
      backgroundColor: colors.mediumBrown,
      transform: "translateY(-1px)",
      boxShadow: `0 4px 8px ${colors.accentGold}4D`,
    },

    viewBtn: {
      display: "flex",
      alignItems: "center",
      gap: "0.3rem",
      backgroundColor: colors.mediumBrown,
      color: colors.lightText,
      border: "none",
      padding: "0.5rem 0.85rem",
      fontSize: "0.75rem",
      borderRadius: "0.5rem",
      cursor: "pointer",
      transition: "all 0.3s ease",
      fontWeight: 500,
      boxShadow: `0 2px 4px ${colors.mediumBrown}33`,
    },

    viewBtnHover: {
      backgroundColor: colors.darkBrown,
      transform: "translateY(-1px)",
      boxShadow: `0 4px 8px ${colors.mediumBrown}4D`,
    },

    // Text Styles
    cancelledText: {
      fontSize: "0.75rem",
      fontWeight: 500,
      color: colors.mediumBrown,
      fontStyle: "italic",
    },

    freeText: {
      fontSize: "0.75rem",
      fontWeight: 500,
      color: colors.mediumBrown,
      fontStyle: "italic",
    },

    // Empty State
    emptyState: {
      padding: "3rem 2rem",
      textAlign: "center",
      backgroundColor: colors.cream,
      borderRadius: "0.75rem",
      border: `1px solid ${colors.lightTan}`,
      color: colors.mediumBrown,
      fontStyle: "italic",
      fontSize: "0.95rem",
    },

    // Note/Label Styles
    formLabel: {
      display: "block",
      fontSize: "0.875rem",
      fontWeight: 600,
      color: colors.darkBrown,
      marginBottom: "0.75rem",
      letterSpacing: "0.025em",
    },

    // Tier Badges (for growth tools)
    tierBadge: {
      padding: "0.35rem 0.8rem",
      borderRadius: "9999px",
      fontSize: "0.75rem",
      fontWeight: 600,
      textTransform: "capitalize",
    },

    tierPremium: {
      backgroundColor: colors.cream,
      color: colors.mediumBrown,
      border: `1px solid ${colors.lightTan}`,
    },

    tierSilver: {
      backgroundColor: colors.offWhite,
      color: colors.darkBrown,
      border: `1px solid ${colors.lightTan}`,
    },

    tierGold: {
      backgroundColor: colors.cream,
      color: colors.mediumBrown,
      border: `1px solid ${colors.lightTan}`,
    },
  };

  // User-type specific configurations
  const userTypeConfigs = {
    investor: {
      tabLabels: ["Subscription History", "Success Fee History"],
      tabKeys: ["billing-history", "billing-info"],
      showGrowthTools: false,
      successFeeColumnNames: {
        transactionId: "Transaction ID",
        counterparty: "SMSE",
        dealValue: "Deal value",
        successFeeAmount: "Success fee amount(3%)",
      },
    },
    catalyst: {
      tabLabels: ["Subscription History", "Success Fee History"],
      tabKeys: ["billing-history", "billing-info"],
      showGrowthTools: false,
      successFeeColumnNames: {
        transactionId: "Transaction ID",
        counterparty: "SMSE",
        dealValue: "Deal value",
        successFeeAmount: "Success fee amount(3%)",
      },
    },
    sme: {
      tabLabels: [
        "Subscription History",
        "Success Fee History",
        "Growth Tools",
      ],
      tabKeys: ["billing-history", "billing-info", "payment-methods"],
      showGrowthTools: true,
      successFeeColumnNames: {
        transactionId: "Transaction ID",
        counterparty: "Investor",
        dealValue: "Deal Value",
        successFeeAmount: "Success Fee Amount",
      },
    },
  };

  // Get user-specific config
  const userConfig = userTypeConfigs[userType] || userTypeConfigs.investor;

  return {
    ...baseStyles,
    userConfig,
  };
};

const getBillingInfoStyles = (isSidebarCollapsed, userType) => ({
  fullPageContainer: {
    display: "flex",
    justifyContent: "center",
    maxWidth: "none",
    marginLeft: isSidebarCollapsed ? "80px" : "280px",
    marginTop: "72px",
    marginBottom: "2rem",
    padding: "0",
    backgroundColor: colors.offWhite,
    borderRadius: "1.25rem",
    boxShadow: `0 10px 25px ${colors.darkBrown}1A`,
    border: `1px solid ${colors.lightTan}`,
    overflow: "hidden",
    transition: "margin-left 0.3s ease",
  },
  contentWrapper: {
    borderRadius: "24px",
    padding: "clamp(1rem, 3vw, 2rem)",
    position: "relative",
    overflow: "hidden",
    maxWidth: "800px",
    width: "100%",
  },
  pageTitle: {
    fontSize: "clamp(2rem, 4vw, 2.75rem)",
    fontWeight: 800,
    background: `linear-gradient(135deg, ${colors.darkBrown} 0%, ${colors.mediumBrown} 100%)`,
    backgroundClip: "text",
    WebkitBackgroundClip: "text",
    color: "transparent",
    textAlign: "center",
    marginBottom: "0.5rem",
    letterSpacing: "-1.5px",
    lineHeight: "1.2",
  },
  subtitle: {
    fontSize: "clamp(1rem, 2vw, 1.125rem)",
    color: colors.mediumBrown,
    textAlign: "center",
    marginBottom: "2rem",
    fontWeight: 400,
    opacity: 0.9,
  },
  formGroup: {
    marginBottom: "1.5rem",
  },
  label: {
    display: "block",
    fontSize: "0.95rem",
    fontWeight: 600,
    color: colors.darkBrown,
    marginBottom: "0.6rem",
  },
  input: {
    width: "100%",
    padding: "0.8rem 1rem",
    borderRadius: "10px",
    border: `1px solid ${colors.lightTan}`,
    backgroundColor: colors.offWhite,
    color: colors.darkText,
    fontSize: "1rem",
    boxShadow: `inset 0 1px 3px ${colors.darkBrown}0A`,
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
  },
  inputFocus: {
    borderColor: colors.accentGold,
    boxShadow: `0 0 0 3px ${colors.accentGold}33`,
    outline: "none",
  },
  error: {
    fontSize: "0.85rem",
    color: colors.featureCross,
    marginTop: "0.5rem",
  },
  button: {
    padding: "1rem 2.5rem",
    background: `linear-gradient(135deg, ${colors.accentGold} 0%, ${colors.mediumBrown} 100%)`,
    color: colors.lightText,
    border: "none",
    borderRadius: "12px",
    fontWeight: 700,
    fontSize: "1rem",
    cursor: "pointer",
    marginTop: "2rem",
    transition: "all 0.3s ease",
    boxShadow: `0 4px 12px ${colors.accentGold}4D`,
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    width: "100%",
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
    background: `linear-gradient(135deg, ${colors.lightTan} 0%, ${colors.cream} 100%)`,
    color: colors.mediumBrown,
    boxShadow: `0 2px 8px ${colors.lightTan}33`,
  },
  loadingSpinner: {
    width: "60px",
    height: "60px",
    border: `4px solid ${colors.lightTan}`,
    borderTop: `4px solid ${colors.accentGold}`,
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    margin: "0 auto 2rem auto",
  },
});

const defaultFields = [
  { label: "Full Name", key: "fullName" },
  { label: "Company Name", key: "companyName" },
  { label: "Email", key: "email", type: "email" },
  { label: "Address", key: "address" },
  { label: "City", key: "city" },
  { label: "State/Region", key: "stateRegion" },
  { label: "Country", key: "country" },
  { label: "Postal Code", key: "postalCode" },
  { label: "Tax ID", key: "taxId" },
];

export {
  getSubStyles,
  getBillingHistoryStyles,
  getBillingInfoStyles,
  defaultFields,
};
