// taxonomyData.js
//
// Offering-category taxonomy library — Developer Brief v1 (29 July 2026), Sections 6-8.
//
// This is the "initial release" library. Per Section 7/17, administrators must be able to
// add, deactivate, merge and alias categories without a code deployment — in production this
// array should be replaced by GET /taxonomy/search + GET /taxonomy/{leaf_id}/config responses.
// It is kept here as a static fixture so the UI is functional and testable before the
// taxonomy API (Developer 1's workstream) is live.
//
// Depth rule reference (Section 6.1):
//   0 - None     : no client operational context adds value (e.g. accounting)
//   1 - Basic    : facility/customer setting affects suitability (e.g. cleaning, catering, guarding)
//   2 - Technical: system/environment/standard affects suitability (e.g. HVAC, medical)
//   3 - Process  : client operation/process area affects matching (e.g. conveyor maintenance, shutdowns)
//   4 - Full     : inherently part of the sector's production route (e.g. production drilling)

let _autoId = 0
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")
const nextLeafId = (domainSlug, catSlug) => `${domainSlug}__${catSlug}__${(_autoId++).toString(36)}`

// Capability profile focus copy, keyed by capability profile id — Section 12, "Capability
// profiles generated by the trigger" table. Used for the offering-card capability badge.
export const capabilityProfiles = {
  product_supply: {
    label: "Product supply",
    focus: "Product range/specifications; source; stockholding; replenishment lead time; order capacity; delivery reach; quality certificates; returns",
  },
  manufacturing_fabrication: {
    label: "Manufacturing / fabrication",
    focus: "Facility; processes; equipment; rated and demonstrated capacity; shifts; quality control; maintenance; output KPIs",
  },
  field_technical_service: {
    label: "Field technical service",
    focus: "Disciplines; technicians; certifications; tools; vehicles; response coverage; concurrent jobs; first-time fix; turnaround",
  },
  project_contractor: {
    label: "Project contractor",
    focus: "Project teams; mobilisation; equipment; subcontractors; project size; schedule performance; safety; quality; references",
  },
  equipment_hire: {
    label: "Equipment hire",
    focus: "Fleet register; capacity rating; certification; availability; utilisation; maintenance; operator provision; mobilisation",
  },
  facilities_service: {
    label: "Facilities service",
    focus: "Teams; shifts; supervision; equipment; consumables; standards; area coverage; service quality; incidents",
  },
  medical_health_service: {
    label: "Medical / health service",
    focus: "Practitioners; registrations; service scope; fixed/mobile capacity; equipment; response; statutory compliance",
  },
  professional_service: {
    label: "Professional service",
    focus: "Disciplines; qualifications; seniority; team capacity; delivery mode; engagements; turnaround; professional registrations",
  },
  logistics_distribution: {
    label: "Logistics / distribution",
    focus: "Fleet or partners; warehouse; geographic reach; payload/storage capacity; tracking; OTIF; lead time; claims",
  },
  training_workforce: {
    label: "Training / workforce",
    focus: "Facilitators; accreditation; venues/platform; class capacity; programmes; placement capacity; completion and outcome measures",
  },
  digital_technology: {
    label: "Digital / technology",
    focus: "Product/platform; hosting; integrations; support model; licences; implementation capacity; uptime/security evidence",
  },
  contract_operations: {
    label: "Contract operations",
    focus: "Operating unit; people; asset systems; capacity; availability; production; quality; maintenance; cost and delivery performance",
  },
  security_emergency: {
    label: "Security / emergency service",
    focus: "Officers; accreditation; response times; equipment; control room; incident reporting; coverage",
  },
  energy_environmental: {
    label: "Energy / environmental solution",
    focus: "System type; installed/rated capacity; compliance; monitoring; maintenance; performance guarantees",
  },
}

// Root domains — Section 7 (both tables). Each has second-level categories and search aliases.
// domainMeta carries the defaults used to drive Section 9-12 dynamic behaviour for any leaf
// under that domain that doesn't have a more specific override in `leaves` below.
const domainMeta = [
  {
    domain: "Contract Production & Operations",
    secondLevel: ["Mining and quarrying operations", "Plant operation", "Production support", "Agricultural operations", "Manufacturing operations", "Utilities operations"],
    aliases: ["contract mining", "load and haul", "plant operator", "farm management"],
    offeringTypes: ["Service"],
    depthLevel: 4,
    capabilityProfile: "contract_operations",
    deliveryPattern: "construction_project",
  },
  {
    domain: "Construction & Project Delivery",
    secondLevel: ["Building works", "Civil works", "Roads and earthworks", "Mechanical works", "Electrical works", "Specialist installation", "Project management"],
    aliases: ["construction", "paving", "concrete", "trenching", "fit-out"],
    offeringTypes: ["Service"],
    depthLevel: 3,
    capabilityProfile: "project_contractor",
    deliveryPattern: "construction_project",
  },
  {
    domain: "Technical & Maintenance Services",
    secondLevel: ["Mechanical", "Electrical", "Instrumentation and control", "HVAC and refrigeration", "Pumps and piping", "Conveyors", "Welding and fabrication", "Condition monitoring", "Shutdowns"],
    aliases: ["aircon", "repairs", "breakdown", "maintenance", "rebuild"],
    offeringTypes: ["Service"],
    depthLevel: 2,
    capabilityProfile: "field_technical_service",
    deliveryPattern: "field_technical_service",
  },
  {
    domain: "Facilities & Site Services",
    secondLevel: ["Cleaning", "Hygiene", "Catering", "Waste", "Landscaping", "Accommodation", "Laundry", "Pest control", "General building maintenance"],
    aliases: ["industrial cleaning", "office cleaning", "camp services"],
    offeringTypes: ["Service"],
    depthLevel: 1,
    capabilityProfile: "facilities_service",
    deliveryPattern: "generic_onsite_virtual_hybrid",
  },
  {
    domain: "Medical, Health & Safety Services",
    secondLevel: ["Occupational health", "Onsite medical", "Mobile clinics", "Emergency response", "Wellness", "Safety consulting", "Hygiene monitoring", "Rehabilitation"],
    aliases: ["clinic", "nurse", "doctor", "ambulance", "OHS"],
    offeringTypes: ["Service"],
    depthLevel: 2,
    capabilityProfile: "medical_health_service",
    deliveryPattern: "medical_service",
  },
  {
    domain: "Equipment Hire & Access",
    secondLevel: ["Earthmoving", "Lifting and rigging", "Access equipment", "Power", "Compressors", "Pumps", "Vehicles", "Tools", "Temporary infrastructure"],
    aliases: ["crane", "hoist", "forklift", "generator", "cherry picker"],
    offeringTypes: ["Product", "Service"],
    depthLevel: 1,
    capabilityProfile: "equipment_hire",
    deliveryPattern: "equipment_hire",
  },
  {
    domain: "Products, Parts & Consumables",
    secondLevel: ["MRO parts", "Electrical", "Mechanical", "Hydraulic", "PPE", "Lubricants", "Chemicals", "Drill consumables", "Cleaning and hygiene", "General stores"],
    aliases: ["bearings", "filters", "valves", "safety boots", "welding rods"],
    offeringTypes: ["Product"],
    depthLevel: 0,
    capabilityProfile: "product_supply",
    deliveryPattern: "physical_product",
  },
  {
    domain: "Machinery, Equipment & Tools",
    secondLevel: ["Production machinery", "Mobile equipment", "Agricultural equipment", "Workshop tools", "Testing equipment", "Medical equipment", "Safety equipment"],
    aliases: ["machine", "excavator", "tractor", "test kit", "tooling"],
    offeringTypes: ["Product"],
    depthLevel: 0,
    capabilityProfile: "product_supply",
    deliveryPattern: "physical_product",
  },
  {
    domain: "Manufacturing & Fabrication",
    secondLevel: ["Metal fabrication", "Machining", "Plastics", "Chemicals", "Food processing", "Textiles", "Components", "Packaging", "Custom manufacture"],
    aliases: ["fabrication", "CNC", "uniforms", "packaging", "components"],
    offeringTypes: ["Product"],
    depthLevel: 1,
    capabilityProfile: "manufacturing_fabrication",
    deliveryPattern: "physical_product",
  },
  {
    domain: "Agricultural Inputs & Products",
    secondLevel: ["Seed", "Fertiliser", "Crop protection", "Animal feed", "Irrigation", "Soil products", "Livestock inputs", "Fresh and processed produce"],
    aliases: ["fertilizer", "seedlings", "irrigation kits", "feed"],
    offeringTypes: ["Product"],
    depthLevel: 1,
    capabilityProfile: "product_supply",
    deliveryPattern: "physical_product",
  },
  {
    domain: "Technology & Digital Services",
    secondLevel: ["Software", "Platforms", "IT support", "Cybersecurity", "Data and analytics", "Automation", "Telecommunications", "Systems integration"],
    aliases: ["app", "ERP", "website", "IT support", "sensors"],
    offeringTypes: ["Product", "Service"],
    depthLevel: 0,
    capabilityProfile: "digital_technology",
    deliveryPattern: "professional_digital_service",
  },
  {
    domain: "Logistics, Warehousing & Distribution",
    secondLevel: ["Road freight", "Courier", "Last mile", "Warehousing", "Cold chain", "Materials handling", "Distribution", "Customs and forwarding"],
    aliases: ["transport", "delivery", "warehouse", "freight"],
    offeringTypes: ["Service"],
    depthLevel: 1,
    capabilityProfile: "logistics_distribution",
    deliveryPattern: "generic_onsite_virtual_hybrid",
  },
  {
    domain: "Professional & Specialist Services",
    secondLevel: ["Accounting", "Audit", "Legal", "Engineering", "Environmental", "Quality", "Strategy", "Marketing", "HR", "Research", "Architecture", "Quantity surveying"],
    aliases: ["bookkeeping", "B-BBEE", "legal", "consulting", "design"],
    offeringTypes: ["Service"],
    depthLevel: 0,
    capabilityProfile: "professional_service",
    deliveryPattern: "professional_digital_service",
  },
  {
    domain: "Training & Workforce Services",
    secondLevel: ["Technical training", "Workplace readiness", "Compliance training", "Recruitment", "Staffing", "Labour hire", "Apprenticeships", "Coaching"],
    aliases: ["training", "interns", "recruitment", "artisans"],
    offeringTypes: ["Service"],
    depthLevel: 1,
    capabilityProfile: "training_workforce",
    deliveryPattern: "training",
  },
  {
    domain: "Security & Emergency Services",
    secondLevel: ["Guarding", "Access control", "Surveillance", "Investigations", "Fire protection", "Rescue", "Emergency planning"],
    aliases: ["security", "CCTV", "fire", "guarding", "response"],
    offeringTypes: ["Service"],
    depthLevel: 1,
    capabilityProfile: "security_emergency",
    deliveryPattern: "generic_onsite_virtual_hybrid",
  },
  {
    domain: "Energy, Water & Environmental Solutions",
    secondLevel: ["Solar", "Backup power", "Energy efficiency", "Water treatment", "Water supply", "Waste recovery", "Rehabilitation", "Environmental monitoring"],
    aliases: ["solar", "borehole", "recycling", "water treatment"],
    offeringTypes: ["Product", "Service"],
    depthLevel: 2,
    capabilityProfile: "energy_environmental",
    deliveryPattern: "field_technical_service",
  },
  {
    domain: "Food, Retail & General Business Supply",
    secondLevel: ["Food and beverages", "Office supplies", "Furniture", "Uniforms", "Promotional products", "General retail", "Corporate gifts"],
    aliases: ["stationery", "catering supplies", "furniture", "uniforms"],
    offeringTypes: ["Product"],
    depthLevel: 0,
    capabilityProfile: "product_supply",
    deliveryPattern: "physical_product",
  },
]

// Explicit searchable leaves — Section 8. Richer than the generated second-level fallback
// leaves below: each carries its own leaf options / examples and, where it materially differs
// from the domain default, its own depth level (Section 6.2 example journeys).
const explicitLeaves = [
  // Technical & Maintenance
  { domain: "Technical & Maintenance Services", category: "HVAC & Refrigeration", options: ["Installation", "Planned maintenance", "Breakdown repair", "Servicing", "Refrigeration systems"], depthLevel: 2, aliases: ["aircon", "air conditioning", "refrigeration", "hvac"] },
  { domain: "Technical & Maintenance Services", category: "Mechanical Maintenance", options: ["Planned maintenance", "Corrective maintenance", "Shutdown maintenance", "Component replacement"], depthLevel: 2, aliases: ["mechanical repair", "breakdown"] },
  { domain: "Technical & Maintenance Services", category: "Electrical Maintenance", options: ["LV/HV installations", "Motors and drives", "Fault finding", "Maintenance", "Testing"], depthLevel: 2, aliases: ["electrician", "electrical repair"] },
  { domain: "Technical & Maintenance Services", category: "Instrumentation & Control", options: ["Calibration", "PLC/SCADA", "Sensors", "Control systems", "Fault finding"], depthLevel: 2, aliases: ["instrumentation", "controls", "scada"] },
  { domain: "Technical & Maintenance Services", category: "Conveyor Services", options: ["Belt splicing", "Idlers", "Pulleys", "Alignment", "Condition monitoring", "Maintenance"], depthLevel: 3, aliases: ["conveyor maintenance", "belt splicing"] },
  { domain: "Technical & Maintenance Services", category: "Pumps, Valves & Piping", options: ["Installation", "Maintenance", "Repair", "Testing", "Dewatering systems"], depthLevel: 2, aliases: ["pump repair", "piping"] },
  { domain: "Technical & Maintenance Services", category: "Shutdown & Turnaround Services", options: ["Planning support", "Mechanical work", "Electrical work", "Execution", "Inspection"], depthLevel: 3, aliases: ["shutdown", "turnaround"] },
  // Facilities & Site Services
  { domain: "Facilities & Site Services", category: "Cleaning Services", options: ["Commercial", "Industrial", "Clinical", "High-level", "Deep cleaning", "Hygiene"], depthLevel: 1, aliases: ["cleaning", "industrial cleaning", "office cleaning"] },
  { domain: "Facilities & Site Services", category: "Waste Management", options: ["General", "Hazardous", "Medical", "Industrial", "Recycling", "Collection"], depthLevel: 1, aliases: ["waste", "refuse", "recycling"] },
  // Medical, Health & Safety
  { domain: "Medical, Health & Safety Services", category: "Occupational Medical Services", options: ["Medical surveillance", "Onsite clinic", "Mobile clinic", "Wellness", "Emergency care"], depthLevel: 2, aliases: ["clinic", "occupational health", "nurse"] },
  { domain: "Medical, Health & Safety Services", category: "Safety Services", options: ["Safety officers", "Risk assessment", "Training", "Audits", "Permit support"], depthLevel: 1, aliases: ["ohs", "safety officer"] },
  // Equipment Hire
  { domain: "Equipment Hire & Access", category: "Lifting & Rigging Equipment", options: ["Cranes", "Hoists", "Chain blocks", "Lifting tackle", "Rigging teams"], depthLevel: 1, aliases: ["crane hire", "hoist hire", "rigging"] },
  { domain: "Equipment Hire & Access", category: "Access Equipment", options: ["MEWPs", "Cherry pickers", "Scaffolding", "Telehandlers", "Ladders"], depthLevel: 1, aliases: ["cherry picker", "scaffolding", "mewp"] },
  { domain: "Equipment Hire & Access", category: "Temporary Power & Utilities", options: ["Generators", "Compressors", "Pumps", "Lighting", "Distribution boards"], depthLevel: 1, aliases: ["generator hire", "compressor hire"] },
  // Products & Consumables
  { domain: "Products, Parts & Consumables", category: "Mechanical MRO Parts", options: ["Bearings", "Seals", "Belts", "Couplings", "Fasteners", "Filters", "Service kits"], depthLevel: 0, aliases: ["bearings", "filters", "mro parts"] },
  { domain: "Products, Parts & Consumables", category: "Electrical Components", options: ["Cables", "Switchgear", "Motors", "Drives", "Lighting", "Connectors"], depthLevel: 0, aliases: ["cables", "switchgear"] },
  { domain: "Products, Parts & Consumables", category: "Hydraulic & Pneumatic Components", options: ["Hoses", "Fittings", "Cylinders", "Valves", "Pumps", "Compressors"], depthLevel: 0, aliases: ["hydraulics", "pneumatics", "valves"] },
  { domain: "Products, Parts & Consumables", category: "PPE & Safety Supplies", options: ["Head", "Eye", "Respiratory", "Hearing", "Hand", "Foot", "Fall protection"], depthLevel: 0, aliases: ["ppe", "safety boots", "safety gear"] },
  { domain: "Products, Parts & Consumables", category: "Industrial Chemicals & Lubricants", options: ["Oils", "Greases", "Cleaning chemicals", "Treatment chemicals", "Gases"], depthLevel: 0, aliases: ["lubricants", "oils", "chemicals"] },
  // Mining Services (under Contract Production & Operations)
  { domain: "Contract Production & Operations", category: "Exploration Drilling", options: ["Core drilling", "RC drilling", "Percussion", "Geotechnical drilling"], depthLevel: 4, aliases: ["exploration drilling", "core drilling"] },
  { domain: "Contract Production & Operations", category: "Production Drilling", options: ["Surface blast-hole", "Underground long-hole", "Development drilling"], depthLevel: 4, aliases: ["production drilling", "blast hole drilling"] },
  { domain: "Contract Production & Operations", category: "Blasting Services", options: ["Charging", "Stemming", "Initiation", "Blast management", "Vibration monitoring"], depthLevel: 4, aliases: ["blasting"] },
  { domain: "Contract Production & Operations", category: "Load & Haul Services", options: ["Loading", "Hauling", "Stockpile management", "Waste movement"], depthLevel: 4, aliases: ["load and haul", "hauling"] },
  { domain: "Contract Production & Operations", category: "Mineral Processing Services", options: ["Crushing", "Screening", "Milling", "Concentration", "Recovery", "Tailings"], depthLevel: 4, aliases: ["mineral processing", "crushing", "screening"] },
  // Construction
  { domain: "Construction & Project Delivery", category: "Earthworks", options: ["Excavation", "Cut and fill", "Grading", "Compaction", "Site clearance"], depthLevel: 3, aliases: ["earthworks", "excavation"] },
  { domain: "Construction & Project Delivery", category: "Civil Works", options: ["Concrete", "Drainage", "Roads", "Pipelines", "Structures", "Rehabilitation"], depthLevel: 3, aliases: ["civil works", "concrete", "drainage"] },
  // Professional Services
  { domain: "Professional & Specialist Services", category: "Engineering Services", options: ["Mechanical", "Electrical", "Civil", "Process", "Mining", "Industrial engineering"], depthLevel: 0, aliases: ["engineering", "consulting engineer"] },
  { domain: "Professional & Specialist Services", category: "Business Advisory", options: ["Strategy", "Finance", "Governance", "Market access", "Operations", "B-BBEE"], depthLevel: 0, aliases: ["consulting", "advisory", "b-bbee"] },
]

function buildTaxonomy() {
  const leaves = []

  for (const meta of domainMeta) {
    const domainSlug = slug(meta.domain)

    // Explicit, richly-specified leaves for this domain (Section 8)
    const own = explicitLeaves.filter((l) => l.domain === meta.domain)
    for (const l of own) {
      const catSlug = slug(l.category)
      leaves.push({
        id: nextLeafId(domainSlug, catSlug),
        domain: meta.domain,
        category: l.category,
        breadcrumb: `${meta.domain} > ${l.category}`,
        leafOptions: l.options,
        searchTerms: [meta.domain, l.category, ...l.options, ...(l.aliases || []), ...meta.aliases].map((s) => s.toLowerCase()),
        offeringTypes: meta.offeringTypes,
        depthLevel: l.depthLevel ?? meta.depthLevel,
        capabilityProfile: meta.capabilityProfile,
        deliveryPattern: meta.deliveryPattern,
        definition: `${l.category} within ${meta.domain}.`,
      })
    }

    // Fallback: generate a leaf per second-level category listed in Section 7 that wasn't
    // already given an explicit, richer entry in Section 8, so every domain stays searchable
    // even before an administrator adds the full leaf breakdown.
    const ownCategoryNames = new Set(own.map((l) => l.category.toLowerCase()))
    for (const secondLevel of meta.secondLevel) {
      if (ownCategoryNames.has(secondLevel.toLowerCase())) continue
      const catSlug = slug(secondLevel)
      leaves.push({
        id: nextLeafId(domainSlug, catSlug),
        domain: meta.domain,
        category: secondLevel,
        breadcrumb: `${meta.domain} > ${secondLevel}`,
        leafOptions: [],
        searchTerms: [meta.domain, secondLevel, ...meta.aliases].map((s) => s.toLowerCase()),
        offeringTypes: meta.offeringTypes,
        depthLevel: meta.depthLevel,
        capabilityProfile: meta.capabilityProfile,
        deliveryPattern: meta.deliveryPattern,
        definition: `${secondLevel} within ${meta.domain}.`,
      })
    }
  }

  return leaves
}

export const taxonomyLeaves = buildTaxonomy()

export const domainList = domainMeta.map((d) => d.domain)

// Section 4.3 search behaviour: begin after 2 characters, match category names, leaf labels,
// aliases and examples, rank exact-phrase / synonym ahead of fuzzy, never restrict by profile
// industries, return at most 8 results.
export function searchTaxonomy(query, { offeringType, industryHints = [] } = {}) {
  const q = (query || "").trim().toLowerCase()
  if (q.length < 2) return []

  let pool = taxonomyLeaves
  if (offeringType && offeringType !== "both") {
    const wanted = offeringType === "products" ? "Product" : "Service"
    pool = pool.filter((l) => l.offeringTypes.includes(wanted))
  }

  const scored = []
  for (const leaf of pool) {
    let score = 0
    const catLower = leaf.category.toLowerCase()
    const domLower = leaf.domain.toLowerCase()

    if (catLower === q) score += 100
    else if (catLower.startsWith(q)) score += 60
    else if (catLower.includes(q)) score += 40

    if (leaf.searchTerms.some((t) => t === q)) score += 80
    else if (leaf.searchTerms.some((t) => t.startsWith(q))) score += 30
    else if (leaf.searchTerms.some((t) => t.includes(q))) score += 15

    if (domLower.includes(q)) score += 10

    // Industry relevance ranks results but never restricts them (Section 4.3 / 11.3).
    if (industryHints.length && industryHints.some((i) => leaf.searchTerms.includes(i.toLowerCase()))) {
      score += 8
    }

    if (score > 0) scored.push({ leaf, score })
  }

  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, 8).map((s) => s.leaf)
}

export function getLeafById(id) {
  return taxonomyLeaves.find((l) => l.id === id) || null
}